name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠️ Refactoring & Maintenance'
    labels:
      - 'refactor'
      - 'cleanup'
      - 'chore'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'dependency'
      - 'deps'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧪 Experimental'
    labels:
      - 'exploration'
      - 'experimental'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## 🌟 What's New in v$NEXT_PATCH_VERSION

  $CHANGES

  ### 🐳 Docker Images

  - **Docker Hub:** `booklore/booklore:v$NEXT_PATCH_VERSION`
  - **GitHub Container Registry:** `ghcr.io/booklore-app/booklore:v$NEXT_PATCH_VERSION`

  **Full Changelog**: https://github.com/booklore-app/booklore/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
