-- Postgres baseline schema. Replaces the 131 MariaDB migrations archived under
-- db/migration-mariadb-archive/ (kept for history only, not on Flyway's classpath).
-- Generated by applying all of them against a throwaway MariaDB instance and translating
-- the resulting end-state schema to Postgres syntax -- see PR description for the process.


-- ============ TABLES ============

CREATE TABLE "annotations" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "cfi" VARCHAR(1000) NOT NULL,
    "text" VARCHAR(5000) NOT NULL,
    "color" VARCHAR(20) DEFAULT NULL,
    "style" VARCHAR(50) DEFAULT NULL,
    "note" VARCHAR(5000) DEFAULT NULL,
    "chapter_title" VARCHAR(500) DEFAULT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "app_migration" (
    "migration_key" VARCHAR(100) NOT NULL,
    "executed_at" TIMESTAMP NOT NULL,
    "description" TEXT DEFAULT NULL,
    PRIMARY KEY ("migration_key")
);

CREATE TABLE "app_settings" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "val" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "audit_log" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT DEFAULT NULL,
    "username" VARCHAR(255) NOT NULL,
    "action" VARCHAR(100) NOT NULL,
    "entity_type" VARCHAR(100) DEFAULT NULL,
    "entity_id" BIGINT DEFAULT NULL,
    "description" VARCHAR(1024) NOT NULL,
    "ip_address" VARCHAR(45) DEFAULT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "country_code" CHAR(2) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "author" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) DEFAULT NULL,
    "description" TEXT DEFAULT NULL,
    "asin" VARCHAR(20) DEFAULT NULL,
    "name_locked" BOOLEAN NOT NULL DEFAULT false,
    "description_locked" BOOLEAN NOT NULL DEFAULT false,
    "asin_locked" BOOLEAN NOT NULL DEFAULT false,
    "photo_locked" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "book" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "library_id" BIGINT NOT NULL,
    "library_path_id" BIGINT DEFAULT NULL,
    "added_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "similar_books_json" TEXT DEFAULT NULL,
    "metadata_match_score" DOUBLE PRECISION DEFAULT NULL,
    "read_status" VARCHAR(20) DEFAULT 'UNREAD',
    "deleted" BOOLEAN DEFAULT false,
    "deleted_at" TIMESTAMP DEFAULT NULL,
    "metadata_updated_at" TIMESTAMP DEFAULT NULL,
    "metadata_for_write_updated_at" TIMESTAMP DEFAULT NULL,
    "book_cover_hash" VARCHAR(20) DEFAULT NULL,
    "is_physical" BOOLEAN NOT NULL DEFAULT false,
    "audiobook_cover_hash" VARCHAR(20) DEFAULT NULL,
    "scanned_on" TIMESTAMP DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "book_award" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "book_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "awarded_at" TIMESTAMP NOT NULL,
    "category" VARCHAR(255) NOT NULL,
    "designation" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "book_file" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "book_id" BIGINT NOT NULL,
    "file_name" VARCHAR(1000) NOT NULL,
    "file_sub_path" VARCHAR(512) NOT NULL,
    "file_size_kb" BIGINT DEFAULT NULL,
    "initial_hash" VARCHAR(128) DEFAULT NULL,
    "current_hash" VARCHAR(128) DEFAULT NULL,
    "description" TEXT DEFAULT NULL,
    "added_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "is_book" BOOLEAN DEFAULT false,
    "book_type" VARCHAR(32) DEFAULT NULL,
    "archive_type" VARCHAR(255) DEFAULT NULL,
    "alt_format_current_hash" VARCHAR(128) GENERATED ALWAYS AS (case when is_book then current_hash end) STORED,
    "is_folder_based" BOOLEAN NOT NULL DEFAULT false,
    "duration_seconds" BIGINT DEFAULT NULL,
    "bitrate" INTEGER DEFAULT NULL,
    "sample_rate" INTEGER DEFAULT NULL,
    "channels" INTEGER DEFAULT NULL,
    "codec" VARCHAR(50) DEFAULT NULL,
    "chapter_count" INTEGER DEFAULT NULL,
    "chapters_json" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "book_marks" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "cfi" VARCHAR(1000) DEFAULT NULL,
    "title" VARCHAR(255) DEFAULT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "color" VARCHAR(7) DEFAULT NULL,
    "notes" VARCHAR(2000) DEFAULT NULL,
    "priority" INTEGER DEFAULT NULL,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "version" BIGINT NOT NULL DEFAULT 1,
    "position_ms" BIGINT DEFAULT NULL,
    "track_index" INTEGER DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "book_metadata" (
    "book_id" BIGINT NOT NULL,
    "title" VARCHAR(1000) DEFAULT NULL,
    "subtitle" VARCHAR(1000) DEFAULT NULL,
    "publisher" VARCHAR(1000) DEFAULT NULL,
    "published_date" DATE DEFAULT NULL,
    "description" TEXT DEFAULT NULL,
    "isbn_13" VARCHAR(64) DEFAULT NULL,
    "isbn_10" VARCHAR(64) DEFAULT NULL,
    "page_count" INTEGER DEFAULT NULL,
    "thumbnail" VARCHAR(2000) DEFAULT NULL,
    "language" VARCHAR(255) DEFAULT NULL,
    "rating" DOUBLE PRECISION DEFAULT NULL,
    "review_count" INTEGER DEFAULT NULL,
    "cover" VARCHAR(2000) DEFAULT NULL,
    "cover_updated_on" TIMESTAMP DEFAULT NULL,
    "series_name" VARCHAR(1000) DEFAULT NULL,
    "series_number" DOUBLE PRECISION DEFAULT NULL,
    "series_total" INTEGER DEFAULT NULL,
    "all_fields_locked" BOOLEAN DEFAULT false,
    "title_locked" BOOLEAN DEFAULT false,
    "authors_locked" BOOLEAN DEFAULT false,
    "categories_locked" BOOLEAN DEFAULT false,
    "subtitle_locked" BOOLEAN DEFAULT false,
    "publisher_locked" BOOLEAN DEFAULT false,
    "published_date_locked" BOOLEAN DEFAULT false,
    "description_locked" BOOLEAN DEFAULT false,
    "isbn_13_locked" BOOLEAN DEFAULT false,
    "isbn_10_locked" BOOLEAN DEFAULT false,
    "page_count_locked" BOOLEAN DEFAULT false,
    "thumbnail_locked" BOOLEAN DEFAULT false,
    "language_locked" BOOLEAN DEFAULT false,
    "cover_locked" BOOLEAN DEFAULT false,
    "rating_locked" BOOLEAN DEFAULT false,
    "review_count_locked" BOOLEAN DEFAULT false,
    "series_name_locked" BOOLEAN DEFAULT false,
    "series_number_locked" BOOLEAN DEFAULT false,
    "series_total_locked" BOOLEAN DEFAULT false,
    "amazon_rating" DOUBLE PRECISION DEFAULT NULL,
    "amazon_review_count" INTEGER DEFAULT NULL,
    "goodreads_rating" DOUBLE PRECISION DEFAULT NULL,
    "goodreads_review_count" INTEGER DEFAULT NULL,
    "amazon_rating_locked" BOOLEAN DEFAULT false,
    "amazon_review_count_locked" BOOLEAN DEFAULT false,
    "goodreads_rating_locked" BOOLEAN DEFAULT false,
    "goodreads_review_count_locked" BOOLEAN DEFAULT false,
    "asin" VARCHAR(20) DEFAULT NULL,
    "asin_locked" BOOLEAN DEFAULT false,
    "hardcover_rating" DOUBLE PRECISION DEFAULT NULL,
    "hardcover_review_count" INTEGER DEFAULT NULL,
    "hardcover_rating_locked" BOOLEAN DEFAULT false,
    "hardcover_review_count_locked" BOOLEAN DEFAULT false,
    "goodreads_id" VARCHAR(100) DEFAULT NULL,
    "hardcover_id" VARCHAR(512) DEFAULT NULL,
    "google_id" VARCHAR(100) DEFAULT NULL,
    "goodreads_id_locked" BOOLEAN DEFAULT false,
    "hardcover_id_locked" BOOLEAN DEFAULT false,
    "google_id_locked" BOOLEAN DEFAULT false,
    "comicvine_id" VARCHAR(100) DEFAULT NULL,
    "comicvine_id_locked" BOOLEAN DEFAULT false,
    "reviews_locked" BOOLEAN DEFAULT false,
    "moods_locked" BOOLEAN DEFAULT false,
    "tags_locked" BOOLEAN DEFAULT false,
    "embedding_vector" TEXT DEFAULT NULL,
    "embedding_updated_at" TIMESTAMP DEFAULT NULL,
    "search_text" TEXT DEFAULT NULL,
    "hardcover_book_id" VARCHAR(100) DEFAULT NULL,
    "hardcover_book_id_locked" BOOLEAN DEFAULT false,
    "lubimyczytac_id" VARCHAR(100) DEFAULT NULL,
    "lubimyczytac_rating" DOUBLE PRECISION DEFAULT NULL,
    "lubimyczytac_id_locked" BOOLEAN DEFAULT false,
    "lubimyczytac_rating_locked" BOOLEAN DEFAULT false,
    "ranobedb_id" VARCHAR(100) DEFAULT NULL,
    "ranobedb_rating" DOUBLE PRECISION DEFAULT NULL,
    "ranobedb_id_locked" BOOLEAN DEFAULT false,
    "ranobedb_rating_locked" BOOLEAN DEFAULT false,
    "audiobook_cover_updated_on" TIMESTAMP DEFAULT NULL,
    "audible_id" VARCHAR(100) DEFAULT NULL,
    "audible_rating" DOUBLE PRECISION DEFAULT NULL,
    "audible_review_count" INTEGER DEFAULT NULL,
    "audible_id_locked" BOOLEAN DEFAULT false,
    "audible_rating_locked" BOOLEAN DEFAULT false,
    "audible_review_count_locked" BOOLEAN DEFAULT false,
    "audiobook_cover_locked" BOOLEAN DEFAULT false,
    "narrator_locked" BOOLEAN DEFAULT false,
    "abridged_locked" BOOLEAN DEFAULT false,
    "narrator" VARCHAR(500) DEFAULT NULL,
    "abridged" BOOLEAN DEFAULT NULL,
    "age_rating" INTEGER DEFAULT NULL,
    "content_rating" VARCHAR(20) DEFAULT NULL,
    "age_rating_locked" BOOLEAN NOT NULL DEFAULT false,
    "content_rating_locked" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("book_id")
);

CREATE TABLE "book_metadata_author_mapping" (
    "book_id" BIGINT NOT NULL,
    "author_id" BIGINT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("book_id", "sort_order")
);

CREATE TABLE "book_metadata_category_mapping" (
    "book_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "category_id")
);

CREATE TABLE "book_metadata_mood_mapping" (
    "book_id" BIGINT NOT NULL,
    "mood_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "mood_id")
);

CREATE TABLE "book_metadata_tag_mapping" (
    "book_id" BIGINT NOT NULL,
    "tag_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "tag_id")
);

CREATE TABLE "book_notes" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "title" VARCHAR(255) DEFAULT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "book_notes_v2" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "cfi" VARCHAR(1000) NOT NULL,
    "selected_text" VARCHAR(5000) DEFAULT NULL,
    "note_content" TEXT NOT NULL,
    "color" VARCHAR(20) DEFAULT NULL,
    "chapter_title" VARCHAR(500) DEFAULT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "book_shelf_mapping" (
    "book_id" BIGINT NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "shelf_id")
);

CREATE TABLE "bookdrop_file" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "file_path" TEXT NOT NULL,
    "file_name" VARCHAR(512) NOT NULL,
    "file_size" BIGINT DEFAULT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING_REVIEW',
    "original_metadata" JSON DEFAULT NULL,
    "fetched_metadata" JSON DEFAULT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "category" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "cbx_viewer_preference" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "spread" VARCHAR(16) DEFAULT NULL,
    "view_mode" VARCHAR(16) DEFAULT NULL,
    "fit_mode" VARCHAR(16) DEFAULT NULL,
    "scroll_mode" VARCHAR(16) DEFAULT NULL,
    "background_color" VARCHAR(16) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "comic_character" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "comic_creator" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "comic_location" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "comic_metadata" (
    "book_id" BIGINT NOT NULL,
    "issue_number" VARCHAR(50) DEFAULT NULL,
    "volume_name" VARCHAR(255) DEFAULT NULL,
    "volume_number" INTEGER DEFAULT NULL,
    "story_arc" VARCHAR(255) DEFAULT NULL,
    "story_arc_number" INTEGER DEFAULT NULL,
    "alternate_series" VARCHAR(255) DEFAULT NULL,
    "alternate_issue" VARCHAR(50) DEFAULT NULL,
    "imprint" VARCHAR(255) DEFAULT NULL,
    "format" VARCHAR(50) DEFAULT NULL,
    "black_and_white" BOOLEAN DEFAULT false,
    "manga" BOOLEAN DEFAULT false,
    "reading_direction" VARCHAR(10) DEFAULT 'ltr',
    "web_link" VARCHAR(1000) DEFAULT NULL,
    "notes" TEXT DEFAULT NULL,
    "issue_number_locked" BOOLEAN DEFAULT false,
    "volume_name_locked" BOOLEAN DEFAULT false,
    "volume_number_locked" BOOLEAN DEFAULT false,
    "story_arc_locked" BOOLEAN DEFAULT false,
    "creators_locked" BOOLEAN DEFAULT false,
    "characters_locked" BOOLEAN DEFAULT false,
    "teams_locked" BOOLEAN DEFAULT false,
    "locations_locked" BOOLEAN DEFAULT false,
    "imprint_locked" BOOLEAN DEFAULT false,
    "format_locked" BOOLEAN DEFAULT false,
    "black_and_white_locked" BOOLEAN DEFAULT false,
    "manga_locked" BOOLEAN DEFAULT false,
    "reading_direction_locked" BOOLEAN DEFAULT false,
    "web_link_locked" BOOLEAN DEFAULT false,
    "notes_locked" BOOLEAN DEFAULT false,
    "story_arc_number_locked" BOOLEAN DEFAULT false,
    "alternate_series_locked" BOOLEAN DEFAULT false,
    "alternate_issue_locked" BOOLEAN DEFAULT false,
    "pencillers_locked" BOOLEAN DEFAULT false,
    "inkers_locked" BOOLEAN DEFAULT false,
    "colorists_locked" BOOLEAN DEFAULT false,
    "letterers_locked" BOOLEAN DEFAULT false,
    "cover_artists_locked" BOOLEAN DEFAULT false,
    "editors_locked" BOOLEAN DEFAULT false,
    PRIMARY KEY ("book_id")
);

CREATE TABLE "comic_metadata_character_mapping" (
    "book_id" BIGINT NOT NULL,
    "character_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "character_id")
);

CREATE TABLE "comic_metadata_creator_mapping" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "book_id" BIGINT NOT NULL,
    "creator_id" BIGINT NOT NULL,
    "role" VARCHAR(20) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "comic_metadata_location_mapping" (
    "book_id" BIGINT NOT NULL,
    "location_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "location_id")
);

CREATE TABLE "comic_metadata_team_mapping" (
    "book_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    PRIMARY KEY ("book_id", "team_id")
);

CREATE TABLE "comic_team" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "custom_font" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "font_name" VARCHAR(255) NOT NULL,
    "file_name" VARCHAR(255) NOT NULL,
    "original_file_name" VARCHAR(255) NOT NULL,
    "format" VARCHAR(10) NOT NULL,
    "file_size" BIGINT NOT NULL,
    "uploaded_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "ebook_viewer_preference" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "font_family" VARCHAR(128) DEFAULT NULL,
    "font_size" INTEGER DEFAULT NULL,
    "gap" DOUBLE PRECISION DEFAULT NULL,
    "hyphenate" BOOLEAN DEFAULT NULL,
    "is_dark" BOOLEAN DEFAULT NULL,
    "justify" BOOLEAN DEFAULT NULL,
    "line_height" DOUBLE PRECISION DEFAULT NULL,
    "max_block_size" INTEGER DEFAULT NULL,
    "max_column_count" INTEGER DEFAULT NULL,
    "max_inline_size" INTEGER DEFAULT NULL,
    "theme" VARCHAR(64) DEFAULT NULL,
    "flow" VARCHAR(32) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "email_provider" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "host" VARCHAR(255) NOT NULL,
    "port" INTEGER NOT NULL,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "from_address" VARCHAR(255) DEFAULT NULL,
    "auth" BOOLEAN NOT NULL,
    "start_tls" BOOLEAN NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "email_provider_v2" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "host" VARCHAR(255) NOT NULL,
    "port" INTEGER NOT NULL,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "from_address" VARCHAR(255) DEFAULT NULL,
    "auth" BOOLEAN NOT NULL,
    "start_tls" BOOLEAN NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "shared" BOOLEAN DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "email_recipient" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "email_recipient_v2" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "epub_viewer_preference" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "theme" VARCHAR(255) DEFAULT NULL,
    "font" VARCHAR(255) DEFAULT NULL,
    "font_size" INTEGER DEFAULT NULL,
    "flow" VARCHAR(32) DEFAULT NULL,
    "letter_spacing" DOUBLE PRECISION DEFAULT NULL,
    "line_height" DOUBLE PRECISION DEFAULT NULL,
    "spread" VARCHAR(20) DEFAULT 'double',
    "custom_font_id" BIGINT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "jwt_secret" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "secret" TEXT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "kobo_library_snapshot" (
    "id" VARCHAR(36) NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_date" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "kobo_library_snapshot_book" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "snapshot_id" VARCHAR(36) NOT NULL,
    "book_id" BIGINT NOT NULL,
    "synced" BOOLEAN NOT NULL DEFAULT false,
    "file_hash" VARCHAR(255) DEFAULT NULL,
    "metadata_updated_at" TIMESTAMP DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "kobo_reading_state" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "entitlement_id" VARCHAR(255) NOT NULL,
    "created" VARCHAR(255) DEFAULT NULL,
    "last_modified" VARCHAR(255) DEFAULT NULL,
    "priority_timestamp" VARCHAR(255) DEFAULT NULL,
    "current_bookmark_json" JSON DEFAULT NULL,
    "statistics_json" JSON DEFAULT NULL,
    "status_info_json" JSON DEFAULT NULL,
    "last_modified_string" VARCHAR(255) DEFAULT NULL,
    "user_id" BIGINT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "kobo_removed_books_tracking" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "snapshot_id" VARCHAR(36) NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id_synced" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "kobo_user_settings" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "token" VARCHAR(2048) NOT NULL,
    "sync_enabled" BOOLEAN NOT NULL DEFAULT true,
    "progress_mark_as_reading_threshold" DOUBLE PRECISION DEFAULT 1,
    "progress_mark_as_finished_threshold" DOUBLE PRECISION DEFAULT 99,
    "auto_add_to_shelf" BOOLEAN NOT NULL DEFAULT false,
    "hardcover_api_key" VARCHAR(2048) DEFAULT NULL,
    "hardcover_sync_enabled" BOOLEAN DEFAULT false,
    "two_way_progress_sync" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "koreader_user" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "username" VARCHAR(100) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "password_md5" VARCHAR(255) NOT NULL,
    "sync_enabled" BOOLEAN DEFAULT NULL,
    "booklore_user_id" BIGINT DEFAULT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "sync_with_booklore_reader" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "library" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "sort" VARCHAR(255) DEFAULT NULL,
    "icon" VARCHAR(64) DEFAULT NULL,
    "watch" BOOLEAN NOT NULL DEFAULT false,
    "file_naming_pattern" VARCHAR(1000) DEFAULT NULL,
    "icon_type" VARCHAR(255) DEFAULT NULL,
    "format_priority" TEXT DEFAULT NULL,
    "organization_mode" VARCHAR(50) DEFAULT 'BOOK_PER_FILE',
    "allowed_formats" TEXT DEFAULT NULL,
    "metadata_source" VARCHAR(20) DEFAULT 'EMBEDDED',
    PRIMARY KEY ("id")
);

CREATE TABLE "library_path" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "path" TEXT DEFAULT NULL,
    "library_id" BIGINT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "magic_shelf" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "icon" VARCHAR(64) DEFAULT NULL,
    "filter_json" JSON NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "is_public" BOOLEAN NOT NULL DEFAULT false,
    "icon_type" VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "metadata_fetch_jobs" (
    "task_id" VARCHAR(100) NOT NULL,
    "user_id" BIGINT DEFAULT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    "status_message" TEXT DEFAULT NULL,
    "started_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP DEFAULT NULL,
    "total_books_count" INTEGER DEFAULT NULL,
    "completed_books" INTEGER DEFAULT 0,
    PRIMARY KEY ("task_id")
);

CREATE TABLE "metadata_fetch_proposals" (
    "proposal_id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "task_id" VARCHAR(100) NOT NULL,
    "book_id" BIGINT NOT NULL,
    "fetched_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "reviewed_at" TIMESTAMP DEFAULT NULL,
    "reviewer_user_id" BIGINT DEFAULT NULL,
    "status" VARCHAR(30) NOT NULL DEFAULT 'pending',
    "metadata_json" JSON NOT NULL,
    PRIMARY KEY ("proposal_id")
);

CREATE TABLE "mood" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "new_pdf_viewer_preference" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "spread" VARCHAR(16) DEFAULT NULL,
    "view_mode" VARCHAR(16) DEFAULT NULL,
    "fit_mode" VARCHAR(16) DEFAULT NULL,
    "scroll_mode" VARCHAR(16) DEFAULT NULL,
    "background_color" VARCHAR(16) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "oidc_group_mapping" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "oidc_group_claim" VARCHAR(255) NOT NULL,
    "is_admin" BOOLEAN NOT NULL DEFAULT false,
    "permissions" TEXT DEFAULT NULL,
    "library_ids" TEXT DEFAULT NULL,
    "description" VARCHAR(500) DEFAULT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "oidc_session" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "oidc_subject" VARCHAR(255) NOT NULL,
    "oidc_issuer" VARCHAR(512) NOT NULL,
    "oidc_session_id" VARCHAR(255) DEFAULT NULL,
    "id_token_hint" TEXT DEFAULT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "last_refreshed_at" TIMESTAMP DEFAULT NULL,
    "revoked" BOOLEAN DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "opds_user" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "opds_user_v2" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "username" VARCHAR(100) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "sort_order" VARCHAR(20) NOT NULL DEFAULT 'RECENT',
    PRIMARY KEY ("id")
);

CREATE TABLE "pdf_annotations" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "data" TEXT NOT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "pdf_viewer_preference" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "zoom" VARCHAR(64) DEFAULT NULL,
    "spread" VARCHAR(64) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "public_book_review" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "metadata_provider" VARCHAR(255) NOT NULL,
    "book_id" BIGINT NOT NULL,
    "reviewer_name" VARCHAR(512) DEFAULT NULL,
    "title" VARCHAR(512) DEFAULT NULL,
    "rating" DOUBLE PRECISION DEFAULT NULL,
    "date" TIMESTAMP DEFAULT NULL,
    "body" TEXT DEFAULT NULL,
    "country" VARCHAR(255) DEFAULT NULL,
    "spoiler" BOOLEAN DEFAULT NULL,
    "followers_count" INTEGER DEFAULT NULL,
    "text_reviews_count" INTEGER DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "reading_sessions" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "book_type" VARCHAR(10) NOT NULL,
    "start_time" TIMESTAMP NOT NULL,
    "end_time" TIMESTAMP NOT NULL,
    "duration_seconds" INTEGER NOT NULL,
    "start_progress" DOUBLE PRECISION DEFAULT NULL,
    "end_progress" DOUBLE PRECISION DEFAULT NULL,
    "progress_delta" DOUBLE PRECISION DEFAULT NULL,
    "start_location" VARCHAR(500) DEFAULT NULL,
    "end_location" VARCHAR(500) DEFAULT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "duration_formatted" VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "refresh_token" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "token" VARCHAR(512) NOT NULL,
    "expiry_date" TIMESTAMP(6) NOT NULL,
    "revoked" BOOLEAN NOT NULL DEFAULT false,
    "revocation_date" TIMESTAMP(6) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "shelf" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "sort" VARCHAR(255) DEFAULT NULL,
    "icon" VARCHAR(64) DEFAULT NULL,
    "icon_type" VARCHAR(255) DEFAULT NULL,
    "is_public" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "tag" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "task_cron_configuration" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "task_type" VARCHAR(100) NOT NULL,
    "cron_expression" VARCHAR(100) NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "created_by" BIGINT NOT NULL DEFAULT -1,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "tasks" (
    "id" VARCHAR(36) NOT NULL,
    "type" VARCHAR(50) NOT NULL,
    "status" VARCHAR(50) NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT NULL,
    "completed_at" TIMESTAMP DEFAULT NULL,
    "progress_percentage" INTEGER DEFAULT NULL,
    "message" TEXT DEFAULT NULL,
    errordetails TEXT DEFAULT NULL,
    "task_options" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_book_file_progress" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_file_id" BIGINT NOT NULL,
    "position_data" VARCHAR(1000) DEFAULT NULL,
    "position_href" VARCHAR(1000) DEFAULT NULL,
    "progress_percent" DOUBLE PRECISION DEFAULT NULL,
    "last_read_time" TIMESTAMP DEFAULT NULL,
    "tts_position_cfi" VARCHAR(1000) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_book_progress" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "last_read_time" TIMESTAMP DEFAULT NULL,
    "pdf_progress" INTEGER DEFAULT NULL,
    "epub_progress" VARCHAR(1000) DEFAULT NULL,
    "pdf_progress_percent" DOUBLE PRECISION DEFAULT NULL,
    "epub_progress_percent" DOUBLE PRECISION DEFAULT NULL,
    "cbx_progress" INTEGER DEFAULT NULL,
    "cbx_progress_percent" DOUBLE PRECISION DEFAULT NULL,
    "read_status" VARCHAR(20) DEFAULT NULL,
    "date_finished" TIMESTAMP DEFAULT NULL,
    "koreader_progress" VARCHAR(1000) DEFAULT NULL,
    "koreader_progress_percent" DOUBLE PRECISION DEFAULT NULL,
    "koreader_device" VARCHAR(100) DEFAULT NULL,
    "koreader_device_id" VARCHAR(100) DEFAULT NULL,
    "koreader_last_sync_time" TIMESTAMP DEFAULT NULL,
    "kobo_progress_percent" DOUBLE PRECISION DEFAULT NULL,
    "kobo_location" VARCHAR(1000) DEFAULT NULL,
    "kobo_location_type" VARCHAR(50) DEFAULT NULL,
    "kobo_location_source" VARCHAR(512) DEFAULT NULL,
    "kobo_progress_received_time" TIMESTAMP DEFAULT NULL,
    "kobo_status_sent_time" TIMESTAMP DEFAULT NULL,
    "read_status_modified_time" TIMESTAMP DEFAULT NULL,
    "kobo_progress_sent_time" TIMESTAMP DEFAULT NULL,
    "personal_rating" SMALLINT DEFAULT NULL,
    "epub_progress_href" VARCHAR(1000) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_content_restriction" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "restriction_type" VARCHAR(20) NOT NULL,
    "mode" VARCHAR(15) NOT NULL,
    "value" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_email_provider_preference" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "default_provider_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_library_mapping" (
    "user_id" BIGINT NOT NULL,
    "library_id" BIGINT NOT NULL,
    PRIMARY KEY ("user_id", "library_id")
);

CREATE TABLE "user_permissions" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "permission_upload" BOOLEAN NOT NULL DEFAULT false,
    "permission_download" BOOLEAN NOT NULL DEFAULT false,
    "permission_edit_metadata" BOOLEAN NOT NULL DEFAULT false,
    "permission_manipulate_library" BOOLEAN NOT NULL DEFAULT false,
    "permission_admin" BOOLEAN NOT NULL DEFAULT false,
    "permission_email_book" BOOLEAN NOT NULL DEFAULT true,
    "permission_delete_book" BOOLEAN NOT NULL DEFAULT false,
    "permission_sync_koreader" BOOLEAN NOT NULL DEFAULT false,
    "permission_sync_kobo" BOOLEAN NOT NULL DEFAULT false,
    "permission_access_opds" BOOLEAN NOT NULL DEFAULT false,
    "permission_manage_metadata_config" BOOLEAN NOT NULL DEFAULT false,
    "permission_access_bookdrop" BOOLEAN NOT NULL DEFAULT false,
    "permission_access_library_stats" BOOLEAN NOT NULL DEFAULT false,
    "permission_access_user_stats" BOOLEAN NOT NULL DEFAULT false,
    "permission_access_task_manager" BOOLEAN NOT NULL DEFAULT false,
    "permission_manage_global_preferences" BOOLEAN NOT NULL DEFAULT false,
    "permission_manage_icons" BOOLEAN NOT NULL DEFAULT false,
    "permission_demo_user" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_auto_fetch_metadata" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_custom_fetch_metadata" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_edit_metadata" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_regenerate_cover" BOOLEAN NOT NULL DEFAULT false,
    "permission_move_organize_files" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_lock_unlock_metadata" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_reset_booklore_read_progress" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_reset_koreader_read_progress" BOOLEAN NOT NULL DEFAULT false,
    "permission_bulk_reset_book_read_status" BOOLEAN NOT NULL DEFAULT false,
    "permission_manage_fonts" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_settings" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "setting_key" VARCHAR(100) NOT NULL,
    "setting_value" TEXT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "users" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "username" VARCHAR(255) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "is_default_password" BOOLEAN NOT NULL DEFAULT true,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) DEFAULT NULL,
    "book_preferences" TEXT DEFAULT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "provisioning_method" VARCHAR(50) DEFAULT NULL,
    "oidc_subject" VARCHAR(255) DEFAULT NULL,
    "oidc_issuer" VARCHAR(512) DEFAULT NULL,
    "avatar_url" VARCHAR(1024) DEFAULT NULL,
    PRIMARY KEY ("id")
);

-- ============ INDEXES ============

CREATE UNIQUE INDEX "annotations__uq_annotation_user_book_cfi" ON "annotations" ("user_id", "book_id", "cfi");
CREATE INDEX "annotations__idx_annotations_user_id" ON "annotations" ("user_id");
CREATE INDEX "annotations__idx_annotations_book_id" ON "annotations" ("book_id");
CREATE INDEX "annotations__idx_annotations_user_book" ON "annotations" ("user_id", "book_id");
CREATE INDEX "annotations__idx_annotations_user_created" ON "annotations" ("user_id", "created_at");
CREATE UNIQUE INDEX "app_settings__uq_app_settings_name" ON "app_settings" ("name");
CREATE INDEX "audit_log__idx_audit_log_created_at" ON "audit_log" ("created_at");
CREATE INDEX "audit_log__idx_audit_log_user_id" ON "audit_log" ("user_id");
CREATE INDEX "audit_log__idx_audit_log_action" ON "audit_log" ("action");
CREATE UNIQUE INDEX "author__unique_name" ON "author" ("name");
CREATE INDEX "author__idx_author_asin" ON "author" ("asin");
CREATE INDEX "book__fk_library_path_id" ON "book" ("library_path_id");
CREATE INDEX "book__idx_library_id" ON "book" ("library_id");
CREATE INDEX "book__idx_book_deleted" ON "book" ("deleted");
CREATE INDEX "book__idx_book_deleted_at" ON "book" ("deleted_at");
CREATE INDEX "book__idx_book_is_physical" ON "book" ("is_physical");
CREATE UNIQUE INDEX "book_award__unique_book_award" ON "book_award" ("book_id", "name", "category", "awarded_at");
CREATE INDEX "book_file__idx_book_additional_file_book_id" ON "book_file" ("book_id");
CREATE INDEX "book_file__idx_book_file_current_hash_alt_format" ON "book_file" ("alt_format_current_hash");
CREATE UNIQUE INDEX "book_marks__uq_user_book_cfi" ON "book_marks" ("user_id", "book_id", "cfi");
CREATE INDEX "book_marks__idx_book_marks_user_id" ON "book_marks" ("user_id");
CREATE INDEX "book_marks__idx_book_marks_book_id" ON "book_marks" ("book_id");
CREATE INDEX "book_marks__idx_bookmark_book_user_priority" ON "book_marks" ("book_id", "user_id", "priority", "created_at");
CREATE INDEX "book_marks__idx_book_marks_user_created" ON "book_marks" ("user_id", "created_at");
CREATE INDEX "book_metadata_author_mapping__idx_book_metadata_id" ON "book_metadata_author_mapping" ("book_id");
CREATE INDEX "book_metadata_author_mapping__idx_author_id" ON "book_metadata_author_mapping" ("author_id");
CREATE INDEX "book_metadata_author_mapping__idx_author_mapping_author_id" ON "book_metadata_author_mapping" ("book_id", "author_id");
CREATE INDEX "book_metadata_category_mapping__fk_book_metadata_category_mapping_category" ON "book_metadata_category_mapping" ("category_id");
CREATE INDEX "book_metadata_mood_mapping__fk_book_metadata_mood_mapping_mood" ON "book_metadata_mood_mapping" ("mood_id");
CREATE INDEX "book_metadata_tag_mapping__fk_book_metadata_tag_mapping_tag" ON "book_metadata_tag_mapping" ("tag_id");
CREATE INDEX "book_notes__idx_book_notes_user_id" ON "book_notes" ("user_id");
CREATE INDEX "book_notes__idx_book_notes_book_id" ON "book_notes" ("book_id");
CREATE UNIQUE INDEX "book_notes_v2__uq_book_notes_v2_user_book_cfi" ON "book_notes_v2" ("user_id", "book_id", "cfi");
CREATE INDEX "book_notes_v2__idx_book_notes_v2_user_id" ON "book_notes_v2" ("user_id");
CREATE INDEX "book_notes_v2__idx_book_notes_v2_book_id" ON "book_notes_v2" ("book_id");
CREATE INDEX "book_notes_v2__idx_book_notes_v2_user_book" ON "book_notes_v2" ("user_id", "book_id");
CREATE INDEX "book_notes_v2__idx_book_notes_v2_user_created" ON "book_notes_v2" ("user_id", "created_at");
CREATE INDEX "book_shelf_mapping__fk_book_shelf_mapping_shelf" ON "book_shelf_mapping" ("shelf_id");
CREATE UNIQUE INDEX "bookdrop_file__uq_file_path" ON "bookdrop_file" ("file_path");
CREATE UNIQUE INDEX "category__name" ON "category" ("name");
CREATE UNIQUE INDEX "cbx_viewer_preference__user_id" ON "cbx_viewer_preference" ("user_id", "book_id");
CREATE UNIQUE INDEX "comic_character__name" ON "comic_character" ("name");
CREATE UNIQUE INDEX "comic_creator__name" ON "comic_creator" ("name");
CREATE UNIQUE INDEX "comic_location__name" ON "comic_location" ("name");
CREATE INDEX "comic_metadata__idx_comic_metadata_story_arc" ON "comic_metadata" ("story_arc");
CREATE INDEX "comic_metadata__idx_comic_metadata_volume_name" ON "comic_metadata" ("volume_name");
CREATE INDEX "comic_metadata_character_mapping__fk_comic_char_mapping_char" ON "comic_metadata_character_mapping" ("character_id");
CREATE INDEX "comic_metadata_creator_mapping__fk_comic_creator_mapping_creator" ON "comic_metadata_creator_mapping" ("creator_id");
CREATE INDEX "comic_metadata_creator_mapping__idx_comic_creator_mapping_role" ON "comic_metadata_creator_mapping" ("role");
CREATE INDEX "comic_metadata_creator_mapping__idx_comic_creator_mapping_book" ON "comic_metadata_creator_mapping" ("book_id");
CREATE INDEX "comic_metadata_location_mapping__fk_comic_loc_mapping_loc" ON "comic_metadata_location_mapping" ("location_id");
CREATE INDEX "comic_metadata_team_mapping__fk_comic_team_mapping_team" ON "comic_metadata_team_mapping" ("team_id");
CREATE UNIQUE INDEX "comic_team__name" ON "comic_team" ("name");
CREATE UNIQUE INDEX "custom_font__file_name" ON "custom_font" ("file_name");
CREATE INDEX "custom_font__idx_user_id" ON "custom_font" ("user_id");
CREATE UNIQUE INDEX "ebook_viewer_preference__user_id" ON "ebook_viewer_preference" ("user_id", "book_id");
CREATE INDEX "ebook_viewer_preference__fk_ebook_viewer_preference_book" ON "ebook_viewer_preference" ("book_id");
CREATE UNIQUE INDEX "email_provider__name" ON "email_provider" ("name", "host", "username");
CREATE UNIQUE INDEX "email_provider_v2__user_id" ON "email_provider_v2" ("user_id", "name");
CREATE INDEX "email_provider_v2__idx_email_provider_v2_user_id" ON "email_provider_v2" ("user_id");
CREATE UNIQUE INDEX "email_recipient__email" ON "email_recipient" ("email");
CREATE UNIQUE INDEX "email_recipient_v2__user_id" ON "email_recipient_v2" ("user_id", "email");
CREATE INDEX "email_recipient_v2__idx_email_recipient_v2_user_id" ON "email_recipient_v2" ("user_id");
CREATE UNIQUE INDEX "epub_viewer_preference__user_id" ON "epub_viewer_preference" ("user_id", "book_id");
CREATE INDEX "epub_viewer_preference__custom_font_id" ON "epub_viewer_preference" ("custom_font_id");
CREATE INDEX "kobo_library_snapshot__fk_snapshot_user" ON "kobo_library_snapshot" ("user_id");
CREATE UNIQUE INDEX "kobo_library_snapshot_book__uq_snapshot_book" ON "kobo_library_snapshot_book" ("snapshot_id", "book_id");
CREATE UNIQUE INDEX "kobo_reading_state__uq_kobo_reading_state_user_entitlement" ON "kobo_reading_state" ("user_id", "entitlement_id");
CREATE INDEX "kobo_reading_state__idx_kobo_reading_state_entitlement_id" ON "kobo_reading_state" ("entitlement_id");
CREATE UNIQUE INDEX "kobo_removed_books_tracking__uq_snapshot_user_book" ON "kobo_removed_books_tracking" ("snapshot_id", "user_id", "book_id_synced");
CREATE UNIQUE INDEX "kobo_user_settings__user_id" ON "kobo_user_settings" ("user_id");
CREATE UNIQUE INDEX "koreader_user__username" ON "koreader_user" ("username");
CREATE INDEX "koreader_user__fk_booklore_user" ON "koreader_user" ("booklore_user_id");
CREATE UNIQUE INDEX "library__name" ON "library" ("name");
CREATE INDEX "library_path__fk_library_path" ON "library_path" ("library_id");
CREATE UNIQUE INDEX "magic_shelf__uq_user_name" ON "magic_shelf" ("user_id", "name");
CREATE INDEX "metadata_fetch_proposals__idx_metadata_proposal_task_id" ON "metadata_fetch_proposals" ("task_id");
CREATE INDEX "metadata_fetch_proposals__idx_metadata_proposal_book_id" ON "metadata_fetch_proposals" ("book_id");
CREATE INDEX "metadata_fetch_proposals__idx_metadata_proposal_status" ON "metadata_fetch_proposals" ("status");
CREATE UNIQUE INDEX "mood__name" ON "mood" ("name");
CREATE UNIQUE INDEX "new_pdf_viewer_preference__user_id" ON "new_pdf_viewer_preference" ("user_id", "book_id");
CREATE UNIQUE INDEX "oidc_group_mapping__oidc_group_claim" ON "oidc_group_mapping" ("oidc_group_claim");
CREATE INDEX "oidc_session__idx_oidc_session_user_id" ON "oidc_session" ("user_id");
CREATE INDEX "oidc_session__idx_oidc_session_subject" ON "oidc_session" ("oidc_subject");
CREATE INDEX "oidc_session__idx_oidc_session_sid" ON "oidc_session" ("oidc_session_id");
CREATE INDEX "oidc_session__idx_oidc_session_sub_iss_revoked" ON "oidc_session" ("oidc_subject", "oidc_issuer", "revoked");
CREATE UNIQUE INDEX "opds_user__username" ON "opds_user" ("username");
CREATE UNIQUE INDEX "opds_user_v2__uq_username" ON "opds_user_v2" ("username");
CREATE INDEX "opds_user_v2__fk_opds_user" ON "opds_user_v2" ("user_id");
CREATE UNIQUE INDEX "pdf_annotations__user_id" ON "pdf_annotations" ("user_id", "book_id");
CREATE INDEX "pdf_annotations__idx_pdf_annotations_user_id" ON "pdf_annotations" ("user_id");
CREATE INDEX "pdf_annotations__idx_pdf_annotations_book_id" ON "pdf_annotations" ("book_id");
CREATE UNIQUE INDEX "pdf_viewer_preference__user_id" ON "pdf_viewer_preference" ("user_id", "book_id");
CREATE INDEX "public_book_review__book_id" ON "public_book_review" ("book_id");
CREATE INDEX "reading_sessions__idx_reading_session_user_time" ON "reading_sessions" ("user_id", "start_time");
CREATE INDEX "reading_sessions__idx_reading_session_book" ON "reading_sessions" ("book_id", "start_time");
CREATE INDEX "reading_sessions__idx_reading_session_user_book" ON "reading_sessions" ("user_id", "book_id", "start_time");
CREATE UNIQUE INDEX "refresh_token__uq_refresh_token" ON "refresh_token" ("token");
CREATE INDEX "refresh_token__fk_refresh_token_user" ON "refresh_token" ("user_id");
CREATE UNIQUE INDEX "shelf__user_id" ON "shelf" ("user_id", "name");
CREATE UNIQUE INDEX "tag__name" ON "tag" ("name");
CREATE UNIQUE INDEX "task_cron_configuration__uq_task_type" ON "task_cron_configuration" ("task_type");
CREATE INDEX "tasks__idx_tasks_user_id" ON "tasks" ("user_id");
CREATE INDEX "tasks__idx_tasks_type" ON "tasks" ("type");
CREATE INDEX "tasks__idx_tasks_status" ON "tasks" ("status");
CREATE INDEX "tasks__idx_tasks_created_at" ON "tasks" ("created_at");
CREATE UNIQUE INDEX "user_book_file_progress__uk_user_book_file" ON "user_book_file_progress" ("user_id", "book_file_id");
CREATE INDEX "user_book_file_progress__fk_ubfp_book_file" ON "user_book_file_progress" ("book_file_id");
CREATE INDEX "user_book_file_progress__idx_ubfp_user_book_file" ON "user_book_file_progress" ("user_id", "book_file_id");
CREATE UNIQUE INDEX "user_book_progress__unique_user_book_progress" ON "user_book_progress" ("user_id", "book_id");
CREATE INDEX "user_book_progress__idx_user_book_progress_user" ON "user_book_progress" ("user_id");
CREATE INDEX "user_book_progress__idx_user_book_progress_book" ON "user_book_progress" ("book_id");
CREATE INDEX "user_book_progress__idx_user_book_progress_date_finished" ON "user_book_progress" ("date_finished");
CREATE UNIQUE INDEX "user_content_restriction__uk_user_restriction" ON "user_content_restriction" ("user_id", "restriction_type", "value");
CREATE INDEX "user_content_restriction__idx_ucr_user_id" ON "user_content_restriction" ("user_id");
CREATE UNIQUE INDEX "user_email_provider_preference__uq_user_id" ON "user_email_provider_preference" ("user_id");
CREATE INDEX "user_email_provider_preference__fk_user_email_preference_provider" ON "user_email_provider_preference" ("default_provider_id");
CREATE INDEX "user_library_mapping__fk_user_library_mapping_library" ON "user_library_mapping" ("library_id");
CREATE INDEX "user_permissions__idx_user_permissions_user" ON "user_permissions" ("user_id");
CREATE UNIQUE INDEX "user_settings__user_id" ON "user_settings" ("user_id", "setting_key");
CREATE UNIQUE INDEX "users__username" ON "users" ("username");
CREATE UNIQUE INDEX "users__email" ON "users" ("email");
CREATE UNIQUE INDEX "users__idx_users_oidc_issuer_subject" ON "users" ("oidc_issuer", "oidc_subject");

-- ============ FOREIGN KEYS ============

ALTER TABLE "annotations" ADD CONSTRAINT "fk_annotations_book_id" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "annotations" ADD CONSTRAINT "fk_annotations_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "book" ADD CONSTRAINT "fk_library" FOREIGN KEY ("library_id") REFERENCES "library" ("id") ON DELETE CASCADE;
ALTER TABLE "book" ADD CONSTRAINT "fk_library_path_id" FOREIGN KEY ("library_path_id") REFERENCES "library_path" ("id") ON DELETE CASCADE;
ALTER TABLE "book_award" ADD CONSTRAINT "fk_book_awards_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_file" ADD CONSTRAINT "fk_book_file_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_marks" ADD CONSTRAINT "fk_book_marks_book_id" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_marks" ADD CONSTRAINT "fk_book_marks_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "book_metadata" ADD CONSTRAINT "fk_book_metadata" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_author_mapping" ADD CONSTRAINT "fk_book_metadata_author_mapping_author" FOREIGN KEY ("author_id") REFERENCES "author" ("id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_author_mapping" ADD CONSTRAINT "fk_book_metadata_author_mapping_book" FOREIGN KEY ("book_id") REFERENCES "book_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_category_mapping" ADD CONSTRAINT "fk_book_metadata_category_mapping_book" FOREIGN KEY ("book_id") REFERENCES "book_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_category_mapping" ADD CONSTRAINT "fk_book_metadata_category_mapping_category" FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_mood_mapping" ADD CONSTRAINT "fk_book_metadata_mood_mapping_book" FOREIGN KEY ("book_id") REFERENCES "book_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_mood_mapping" ADD CONSTRAINT "fk_book_metadata_mood_mapping_mood" FOREIGN KEY ("mood_id") REFERENCES "mood" ("id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_tag_mapping" ADD CONSTRAINT "fk_book_metadata_tag_mapping_book" FOREIGN KEY ("book_id") REFERENCES "book_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "book_metadata_tag_mapping" ADD CONSTRAINT "fk_book_metadata_tag_mapping_tag" FOREIGN KEY ("tag_id") REFERENCES "tag" ("id") ON DELETE CASCADE;
ALTER TABLE "book_notes" ADD CONSTRAINT "fk_book_notes_book_id" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_notes" ADD CONSTRAINT "fk_book_notes_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "book_notes_v2" ADD CONSTRAINT "fk_book_notes_v2_book_id" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_notes_v2" ADD CONSTRAINT "fk_book_notes_v2_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "book_shelf_mapping" ADD CONSTRAINT "fk_book_shelf_mapping_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "book_shelf_mapping" ADD CONSTRAINT "fk_book_shelf_mapping_shelf" FOREIGN KEY ("shelf_id") REFERENCES "shelf" ("id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata" ADD CONSTRAINT "fk_comic_metadata_book" FOREIGN KEY ("book_id") REFERENCES "book_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_character_mapping" ADD CONSTRAINT "fk_comic_char_mapping_book" FOREIGN KEY ("book_id") REFERENCES "comic_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_character_mapping" ADD CONSTRAINT "fk_comic_char_mapping_char" FOREIGN KEY ("character_id") REFERENCES "comic_character" ("id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_creator_mapping" ADD CONSTRAINT "fk_comic_creator_mapping_book" FOREIGN KEY ("book_id") REFERENCES "comic_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_creator_mapping" ADD CONSTRAINT "fk_comic_creator_mapping_creator" FOREIGN KEY ("creator_id") REFERENCES "comic_creator" ("id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_location_mapping" ADD CONSTRAINT "fk_comic_loc_mapping_book" FOREIGN KEY ("book_id") REFERENCES "comic_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_location_mapping" ADD CONSTRAINT "fk_comic_loc_mapping_loc" FOREIGN KEY ("location_id") REFERENCES "comic_location" ("id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_team_mapping" ADD CONSTRAINT "fk_comic_team_mapping_book" FOREIGN KEY ("book_id") REFERENCES "comic_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "comic_metadata_team_mapping" ADD CONSTRAINT "fk_comic_team_mapping_team" FOREIGN KEY ("team_id") REFERENCES "comic_team" ("id") ON DELETE CASCADE;
ALTER TABLE "custom_font" ADD CONSTRAINT "custom_font_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "ebook_viewer_preference" ADD CONSTRAINT "fk_ebook_viewer_preference_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "ebook_viewer_preference" ADD CONSTRAINT "fk_ebook_viewer_preference_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "email_provider_v2" ADD CONSTRAINT "fk_email_provider_v2_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "email_recipient_v2" ADD CONSTRAINT "fk_email_recipient_v2_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "epub_viewer_preference" ADD CONSTRAINT "epub_viewer_preference_ibfk_1" FOREIGN KEY ("custom_font_id") REFERENCES "custom_font" ("id") ON DELETE SET NULL;
ALTER TABLE "kobo_library_snapshot" ADD CONSTRAINT "fk_snapshot_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "kobo_library_snapshot_book" ADD CONSTRAINT "fk_snapshot_book" FOREIGN KEY ("snapshot_id") REFERENCES "kobo_library_snapshot" ("id") ON DELETE CASCADE;
ALTER TABLE "kobo_reading_state" ADD CONSTRAINT "fk_kobo_reading_state_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "kobo_removed_books_tracking" ADD CONSTRAINT "fk_removed_snapshot" FOREIGN KEY ("snapshot_id") REFERENCES "kobo_library_snapshot" ("id") ON DELETE CASCADE;
ALTER TABLE "kobo_user_settings" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "koreader_user" ADD CONSTRAINT "fk_booklore_user" FOREIGN KEY ("booklore_user_id") REFERENCES "users" ("id");
ALTER TABLE "library_path" ADD CONSTRAINT "fk_library_path" FOREIGN KEY ("library_id") REFERENCES "library" ("id") ON DELETE CASCADE;
ALTER TABLE "metadata_fetch_proposals" ADD CONSTRAINT "fk_metadata_fetch_task" FOREIGN KEY ("task_id") REFERENCES "metadata_fetch_jobs" ("task_id") ON DELETE CASCADE;
ALTER TABLE "oidc_session" ADD CONSTRAINT "fk_oidc_session_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "opds_user_v2" ADD CONSTRAINT "fk_opds_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "pdf_annotations" ADD CONSTRAINT "fk_pdf_annotations_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "pdf_annotations" ADD CONSTRAINT "fk_pdf_annotations_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "public_book_review" ADD CONSTRAINT "public_book_review_ibfk_1" FOREIGN KEY ("book_id") REFERENCES "book_metadata" ("book_id") ON DELETE CASCADE;
ALTER TABLE "reading_sessions" ADD CONSTRAINT "fk_reading_session_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "reading_sessions" ADD CONSTRAINT "fk_reading_session_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "refresh_token" ADD CONSTRAINT "fk_refresh_token_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "shelf" ADD CONSTRAINT "fk_shelf_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_book_file_progress" ADD CONSTRAINT "fk_ubfp_book_file" FOREIGN KEY ("book_file_id") REFERENCES "book_file" ("id") ON DELETE CASCADE;
ALTER TABLE "user_book_file_progress" ADD CONSTRAINT "fk_ubfp_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_book_progress" ADD CONSTRAINT "fk_user_book_progress_book" FOREIGN KEY ("book_id") REFERENCES "book" ("id") ON DELETE CASCADE;
ALTER TABLE "user_book_progress" ADD CONSTRAINT "fk_user_book_progress_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_content_restriction" ADD CONSTRAINT "fk_ucr_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_email_provider_preference" ADD CONSTRAINT "fk_user_email_preference_provider" FOREIGN KEY ("default_provider_id") REFERENCES "email_provider_v2" ("id") ON DELETE CASCADE;
ALTER TABLE "user_email_provider_preference" ADD CONSTRAINT "fk_user_email_preference_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_library_mapping" ADD CONSTRAINT "fk_user_library_mapping_library" FOREIGN KEY ("library_id") REFERENCES "library" ("id") ON DELETE CASCADE;
ALTER TABLE "user_library_mapping" ADD CONSTRAINT "fk_user_library_mapping_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_permissions" ADD CONSTRAINT "fk_user_permissions_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

-- ============ COLUMN COMMENTS ============

COMMENT ON COLUMN "app_migration"."migration_key" IS 'Unique identifier for the migration';
COMMENT ON COLUMN "app_migration"."executed_at" IS 'When the migration was executed';
COMMENT ON COLUMN "app_migration"."description" IS 'Optional description of what the migration did';

-- ============ updated_at TRIGGER TABLES (manual) ============
-- book_notes, bookdrop_file, koreader_user, magic_shelf, oidc_group_mapping, opds_user_v2, task_cron_configuration, user_settings

-- ============ updated_at TRIGGER ============

CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_book_notes_updated_at BEFORE UPDATE ON "book_notes" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_bookdrop_file_updated_at BEFORE UPDATE ON "bookdrop_file" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_koreader_user_updated_at BEFORE UPDATE ON "koreader_user" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_magic_shelf_updated_at BEFORE UPDATE ON "magic_shelf" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_oidc_group_mapping_updated_at BEFORE UPDATE ON "oidc_group_mapping" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_opds_user_v2_updated_at BEFORE UPDATE ON "opds_user_v2" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_task_cron_configuration_updated_at BEFORE UPDATE ON "task_cron_configuration" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_settings_updated_at BEFORE UPDATE ON "user_settings" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
